# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Melissa's Food Blog! v1.0"
email: Oconnellmelissa89@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about Food!
  Content by <a href='http://foodissa.github.io/about'>Melissa OConnell</a>
  design&development by <a href='http://github.com/wommy' target='_blank'>Wommy</a>
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://foodissa.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

# prose
prose:
  rooturl: '_posts'
  siteurl: 'http://foodissa.github.io/'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "date"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
          
